name: 'setup environment'
description: 'setup go environment'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version: ${{ env.GO_VERSION }}
        cache-dependency-path: '**/go.sum'

    - name: Installing required tools
      run: |
        make install-tools
      shell: bash
