// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("monitor")
	ScopeName = "github.com/splunk/tarunner/internal/monitorreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
