name: OSS Scan
jobs:
  fossa-scan:
    uses: splunk/oss-scanning-public/.github/workflows/oss-scan.yml@a9f2984bb2cca5d40994956f8f428150b8eca4b7 # main
    secrets: inherit
on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - opened